import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import NewsLetter from "./components/common/news-letter/NewsLetter";
import Footer from "./components/common/footer/Footer";
import NavbarSec from "./components/common/navbar/NavbarSec";

const PlaypenSans = Playpen_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PlaypenSans.className}>
        <NavbarSec/>
        {children}
        <NewsLetter/>
        <Footer/>
      </body>
    </html>
  );
}
